server:
  port : 80
  
spring:
  profiles: 
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: skmns
    password: 1234  

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      